name: Code quality

on:
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Print elixir version
        run: elixir --version

      - name: Install dependencies
        run: mix deps.get

      - name: Linting
        run: mix format --check-formatted
