name: Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04

    services:
      # run postgres in a service container
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - uses: actions/checkout@v5
      - uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Print elixir version
        run: elixir --version

      - name: Install dependencies
        run: mix deps.get

      - name: Tests
        run: mix test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
